In [1]:
import numpy as np
import pandas as pd
import keras 
from sklearn import datasets
from sklearn.model_selection import train_test_split
# importing libraries

In [2]:
iris = datasets.load_iris()
x = iris.data
print(x.shape)
y = iris.target
y.shape

(150, 4)


(150,)

In [3]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2 , random_state=42)


In [4]:
model = keras.models.Sequential()
model.add(keras.layers.Dense(4, activation='relu', input_shape = (4,)))
model.add(keras.layers.Dense(4, activation='relu'))
model.add(keras.layers.Dense(3, activation='softmax'))

c:\Users\parsa\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [5]:
model.compile(optimizer= 'adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])



x_train = np.array(x_train)
y_train = np.array(y_train)

model.fit(x_train, y_train, epochs=30 , batch_size=5
          )


Epoch 1/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.3703 - loss: 7.7961
Epoch 2/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.2680 - loss: 7.0637 
Epoch 3/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3138 - loss: 5.2183 
Epoch 4/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.3696 - loss: 3.6231 
Epoch 5/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.3187 - loss: 2.6513     
Epoch 6/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.2997 - loss: 1.9502 
Epoch 7/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.2576 - loss: 1.8731     
Epoch 8/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4317 - loss: 1.6105 
Epoch 9/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5888 - loss: 1.3056 
Epoch 10/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6842 - loss: 1.1326 
Epoch 11/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6736 - loss: 0.9898 
Epoch 12/30
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - acc

In [6]:
loss, accuracy = model.evaluate(x_test, y_test)
print(f'loss: {loss}, Accuracy: {accuracy}')
predictions = model.predict(x_test)
print(predictions)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step - accuracy: 0.9667 - loss: 0.4057
loss: 0.40572959184646606, Accuracy: 0.9666666388511658
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step
[[0.07578941 0.5371217  0.38708884]
 [0.96008694 0.02340948 0.0165035 ]
 [0.00842976 0.38311133 0.6084589 ]
 [0.05263448 0.48210058 0.46526498]
 [0.05021286 0.49893185 0.4508553 ]
 [0.9269468  0.04297346 0.03007973]
 [0.1264435  0.4970869  0.3764696 ]
 [0.00834482 0.30747953 0.68417567]
 [0.02788034 0.44619778 0.5259218 ]
 [0.10895776 0.51642513 0.3746172 ]
 [0.01757793 0.38443938 0.5979827 ]
 [0.9489051  0.0310238  0.020071  ]
 [0.96221435 0.02186436 0.01592123]
 [0.9515945  0.02935824 0.01904734]
 [0.9555548  0.02636749 0.01807779]
 [0.05561163 0.47987086 0.4645175 ]
 [0.010053   0.35925096 0.63069594]
 [0.10941461 0.5278142  0.3627712 ]
 [0.06984093 0.51772934 0.41242975]
 [0.0103164  0.35506034 0.63462317]
 [0.93763566 0.03825163 0.02411269]
 [0.02476118 0.42157534 0.55366343]
 [0.91791743 0.04943866 0.03264392]
 [0.0